site_name: ISEE/IS Training Course

nav:
  - 事前準備: setup.md
  - Linux入門: linux_usage.md
  - Git/GitHub入門: git_github.md
  - VSCode入門: vscode.md
  - Python入門: python.md
  - データ解析入門: data_analysis.md
  - 数値計算入門: numerical_simulation.md
  - 参考文献: references.md

theme: readthedocs

markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
