site_name: 総合解析トレーニングコース

nav:
  - このコースの目的: index.md
  - 事前準備: setup.md
  - Linux入門:
    - LinuxとUNIX系OS: linux/linux_and_unix.md
    - シェルとターミナル: linux/shell.md
    - ヘルプとマニュアル: linux/help_and_man.md
    - ファイル・ディレクトリの操作: linux/file_and_directory.md
    - テキストファイルの操作: linux/text_file.md
    - プロセスの操作: linux/process.md
    - システム情報の利用: linux/system.md
  - 計算機ネットワーク入門:
    - ネットワークの基本的な仕組み: network/tcp_ip.md
    - 便利なネットワークコマンド: network/command.md
    - 補足情報: network/appendix.md
  - Git/GitHub入門:
    - バージョン管理とGit: git_github/versioning.md
    - Gitを使ってみよう: git_github/git_local.md
    - リモートリポジトリの活用: git_github/git_remote.md
    - GitHubを使ってみよう: git_github/github.md
    - 共同開発を始めよう: git_github/collaboration.md
  - VSCode入門(執筆中): vscode.md
  - 作業の自動化:
    - 研究と自動化: automation/need.md
    - シェルスクリプト: automation/shell_script.md
    - make と Makefile: automation/makefile.md
    - 仮想化とコンテナ: automation/container.md
  - Python入門:
    - 事前準備: python/prep.md
    - 基礎文法: python/basic.md
    - ライブラリ: python/library.md
    - 仮想環境: python/venv.md
  - データ解析入門(執筆中): data_analysis.md
  - 数値計算入門(執筆中): numerical_simulation.md
  - サーバー管理の手引き: server_management.md
  - 参考文献: references.md

theme:
  name: material
  language: ja
  features:
    - header.autohide
    - content.code.copy
    # - toc.integrate
    # - navigation.tabs
    # - navigation.expand
    # - navigation.sections
  palette:
    primary: blue grey

copyright: Copyright &copy; 2025 Division for Integrated Studies, Institute for Space-Earth Environmental Research, Nagoya UNIVERSITY.
repo_url: https://github.com/is-isee/training_course

markdown_extensions:
  - toc:
      toc_depth: 3
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
