site_name: 総合解析トレーニングコース

nav:
  - ホーム: index.md
  - 事前準備: setup.md
  - Linux入門: linux_usage.md
  - ネットワーク入門: network.md
  - Git/GitHub入門: git_github.md
  - VSCode入門: vscode.md
  - Python入門: python.md
  - データ解析入門: data_analysis.md
  - 数値計算入門: numerical_simulation.md
  - 参考文献: references.md

theme:
  # name: 'readthedocs'
  name: material
  language: ja
  features:
    - header.autohide

copyright: Copyright &copy; 2025 Division for Integrated Studies, Institute for Space-Earth Environmental Research, Nagoya UNIVERSITY.
repo_url: https://github.com/is-isee/training_course

markdown_extensions:
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
